CREATE TABLE music_table (
    id INT AUTO_INCREMENT PRIMARY KEY,
    track_name VARCHAR(255),
    artists_name VARCHAR(255),
    artist_count INT,
    released_year INT,
    released_month INT,
    released_day INT,
    in_spotify_playlists INT,
    in_spotify_charts INT,
    streams BIGINT,
    in_apple_playlists INT,
    in_apple_charts INT,
    in_deezer_playlists INT,
    in_deezer_charts INT,
    in_shazam_charts INT,
    bpm INT,
    key_ VARCHAR(3),
    mode_ VARCHAR(10),
    danceability FLOAT,
    valence FLOAT,
    energy FLOAT,
    acousticness FLOAT,
    instrumentalness FLOAT,
    liveness FLOAT,
    speechiness FLOAT
);
